services:
  - type: web
    name: khang-3d-portfolio
    runtime: node
    plan: free
    region: singapore
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
